[[language]]
name = "python"
language-servers = ["pylsp"]

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }

[[language]]
name = "cpp"
formatter = { command = "clang-format" }
auto-format = true

[[language]]
name = "rust"
formatter = { command = "rustfmt" }
auto-format = true

[language-server.pylsp.config.pylsp]
plugins.pylsp_mypy.enabled = true
plugins.pylsp_mypy.live_mode = true

[language-server.rust-analyzer.config.check]
command = "clippy"
